### ISSUE TITLE
Invalid emass.json "systemID" (it is not an integer nor valid for eMASS) repo is not showing up in the dashboard

### ISSUE THREAD

**Issue by Boberski** [department-of-veterans-affairs/codeql-tools#67] opened 2023-08-23 15:57 UTC
We have another bug it looks like. It showed up on the `SEPS` repo. While it has an invalid `emass.json` "systemID" (it is not an integer nor valid for eMASS), it is not showing up in the dashboard. Tool health is green, no error messages otherwise when looking at that repo. When looking at the `code-scanning-governance-platform` repo's `Generate Metrics` job, we see starting on line 27513, then on 27519 `Failed processing repository [department-of-veterans-affairs/SEPS], skipping: failed retrieving emass.json`. So looks like a fix is needed.

**Comment by lindluni** [comment] 2023-08-23 19:16
Thanks for reporting this Mike, I believe I have a solution for this which is caused by Javascript not being able to differentiate between `1.0` and `1`, I am testing that fix now.

**Comment by lindluni** [comment] 2023-08-24 02:03
Fixed in https://github.com/department-of-veterans-affairs/codeql-tools/commit/2815d74782623367f06055164c5a247ccf101cf1 and tested

**Comment by lindluni** [comment] 2023-08-24 02:04
Failed scans due to invalid values do in fact raise those issues to the GitHub UI as well: 
![image](https://github.com/department-of-veterans-affairs/codeql-tools/assets/9400927/fa4e7ad1-76c7-45f3-9471-9cb38daa1e82)

**Closed** 2023-08-24 02:05 UTC
